FROM curlimages/curl:8.5.0

# Switch to root
USER root

# This image already has curl, just add ca-certificates
RUN apk add --no-cache ca-certificates

# Copy certificate
COPY mitmproxy-ca.pem /usr/local/share/ca-certificates/mitmproxy.crt

# Update certificates
RUN update-ca-certificates

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

WORKDIR /app
CMD ["/bin/sh"]
